import Head from "next/head";
import { useRouter } from "next/router";
import { Button } from "@chakra-ui/react";
import { useEffect } from "react";

import useMe from "../hooks/useMe";

export default function LandingPage() {
  const router = useRouter();
  const { me, isLoading, isError } = useMe();

  // Redirect to home if signed in
  useEffect(() => {
    if (me?.auth && !isLoading) {
      router.replace("/home");
    }
  }, [me, isLoading, router]);

  if (isError) {
    return <p>There was an error</p>;
  }

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (me && !me.auth) {
    return (
      <div>
        <Head>
          <title>Diverse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <p>Spotty</p>
        <Button as="a" href={"/api/oauth"}>
          Log In With Spotify
        </Button>

        <button onClick={() => setValue((prev) => prev + 1)}>Click</button>

        <Button as="a" href={"/api/test"}>
          Test DB
        </Button>
      </div>
    );
  }

  return <p>Redirecting...</p>;
}
